spring:
  output:
    ansi:
      # Activamos los colorines al arranque
      enabled: ALWAYS
  application:
    name: backendDevTest

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

# Puerto del servidor
server:
  port: 5000

rest-integration:
  timeout: 60000
  systems:
    EXISTING_APIS:
      urlBase: "http://localhost:3001"
      endpoints:
        SIMILAR_PRODUCTS:
          url: "${rest-integration.systems.EXISTING_APIS.urlBase}/product/{productId}/similarids"
          method: GET
        PRODUCT_DETAIL:
          url: "${rest-integration.systems.EXISTING_APIS.urlBase}/product/{productId}"
          method: GET